-- Questões de exemplo no formato do contrato v1. Cobrem: múltipla escolha, Certo/Errado,
-- grupo com texto de apoio (e recorte de apoio repetido em cada questão do grupo), figura
-- no enunciado e em alternativa, anulada, sem gabarito, inconsistente, gabarito preliminar
-- e questão ainda sem classificação. IDs propositalmente não sequenciais.

INSERT INTO fx_questao_estudo (questao_id, prova_id, banca, orgao, ano, cargo, area_prova,
  tipo_caderno, numero, tipo_item, enunciado, texto_apoio, gabarito_status, resposta_correta,
  gabarito_versao, tipo_cobranca, tipo_cobranca_confianca, nivel_cognitivo,
  nivel_cognitivo_confianca, norma_referencia, classificada, tem_recorte) VALUES
(101, 10, 'cesgranrio', 'Petrobras', 2023, 'Analista de Sistemas', 'Infraestrutura', '1', 31,
 'multipla_escolha',
 'Uma relação está na terceira forma normal (3FN) quando está na 2FN e',
 NULL, 'ok', 'B', 'definitivo', 'definicao', 0.92, 'lembrar', 0.88, NULL, true, false),
(102, 10, 'cesgranrio', 'Petrobras', 2023, 'Analista de Sistemas', 'Infraestrutura', '1', 32,
 'multipla_escolha',
 'Considere o diagrama apresentado em [FIGURA 1]. Qual é a cardinalidade entre PEDIDO e ITEM?',
 NULL, 'ok', 'D', 'definitivo', 'leitura_de_codigo', 0.61, 'analisar', 0.7, NULL, true, true),
(205, 20, 'cebraspe', 'TCU', 2022, 'Auditor Federal de Controle Externo', 'Tecnologia da Informação',
 NULL, 41, 'certo_errado',
 'De acordo com o texto, o protocolo TLS 1.3 eliminou o handshake RSA estático.',
 'Texto CB1A1. O TLS 1.3 simplificou o handshake, removeu suítes legadas e passou a exigir sigilo direto (forward secrecy). Observe a [FIGURA 1].',
 'ok', 'C', 'definitivo', 'estudo_de_caso', 0.8, 'entender', 0.75, NULL, true, true),
(206, 20, 'cebraspe', 'TCU', 2022, 'Auditor Federal de Controle Externo', 'Tecnologia da Informação',
 NULL, 42, 'certo_errado',
 'Infere-se do texto que o TLS 1.3 mantém compatibilidade total com suítes de cifra do TLS 1.0.',
 'Texto CB1A1. O TLS 1.3 simplificou o handshake, removeu suítes legadas e passou a exigir sigilo direto (forward secrecy). Observe a [FIGURA 1].',
 'ok', 'E', 'preliminar', 'estudo_de_caso', 0.79, 'entender', 0.72, NULL, true, true),
(207, 20, 'cebraspe', 'TCU', 2022, 'Auditor Federal de Controle Externo', 'Tecnologia da Informação',
 NULL, 43, 'certo_errado',
 'Nos termos da LGPD, o encarregado deve ser obrigatoriamente pessoa física.',
 NULL, 'anulada', NULL, 'definitivo', 'letra_de_lei', 0.9, 'lembrar', 0.8,
 'Lei 13.709/2018', true, false),
(310, 31, 'fgv', 'Senado Federal', NULL, 'Analista Legislativo', NULL, NULL, 12,
 'multipla_escolha',
 'Em Java, qual é a saída do trecho de código abaixo? [FIGURA 1]',
 NULL, 'sem_gabarito', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, true),
(311, 31, 'fgv', 'Senado Federal', NULL, 'Analista Legislativo', NULL, NULL, 13,
 'multipla_escolha',
 'Assinale a alternativa que apresenta o gráfico de uma árvore AVL balanceada.',
 NULL, 'inconsistente', NULL, 'definitivo', NULL, NULL, NULL, NULL, NULL, false, true),
(415, 40, 'fcc', 'TRT 2ª Região', 2019, 'Analista Judiciário', 'Apoio Especializado — TI', 'A', 55,
 'multipla_escolha',
 'No PostgreSQL, o comando que remove linhas mortas e atualiza estatísticas do planejador é',
 NULL, 'ok', 'A', 'definitivo', NULL, NULL, 'lembrar', 0.66, NULL, true, false),
(520, 50, 'vunesp', 'Prefeitura de São Paulo', 2024, 'Analista de TI', NULL, NULL, 7,
 'multipla_escolha',
 'O princípio SOLID que recomenda depender de abstrações e não de implementações é o',
 NULL, 'ok', 'E', 'definitivo', 'definicao', 0.95, 'lembrar', 0.9, NULL, true, false);

INSERT INTO fx_questao_alternativa (questao_id, letra, texto) VALUES
(101, 'A', 'todos os atributos são atômicos.'),
(101, 'B', 'nenhum atributo não chave depende transitivamente da chave primária.'),
(101, 'C', 'toda dependência funcional tem uma superchave como determinante.'),
(101, 'D', 'não há dependências multivaloradas.'),
(101, 'E', 'não há dependências de junção.'),
(102, 'A', '1:1'),
(102, 'B', '0:1'),
(102, 'C', 'N:M'),
(102, 'D', '1:N'),
(102, 'E', 'Não é possível determinar.'),
(310, 'A', '0'),
(310, 'B', '1'),
(310, 'C', '10'),
(310, 'D', 'Erro de compilação.'),
(310, 'E', 'Exceção em tempo de execução.'),
(311, 'A', '[FIGURA 1]'),
(311, 'B', '[FIGURA 2]'),
(311, 'C', '[FIGURA 3]'),
(311, 'D', 'Nenhuma das árvores é AVL.'),
(415, 'A', 'VACUUM ANALYZE.'),
(415, 'B', 'REINDEX.'),
(415, 'C', 'CLUSTER.'),
(415, 'D', 'TRUNCATE.'),
(415, 'E', 'CHECKPOINT.'),
(520, 'A', 'da responsabilidade única.'),
(520, 'B', 'aberto/fechado.'),
(520, 'C', 'da substituição de Liskov.'),
(520, 'D', 'da segregação de interfaces.'),
(520, 'E', 'da inversão de dependência.');

INSERT INTO fx_questao_topico (questao_id, area_id, area, topico_id, topico, principal, confianca) VALUES
(101, 1, 'Banco de Dados', 11, 'Normalização', true, 0.93),
(102, 1, 'Banco de Dados', 12, 'Modelagem de Dados', true, 0.81),
(205, 2, 'Segurança da Informação', 21, 'Criptografia', true, 0.86),
(205, 3, 'Redes de Computadores', 31, 'Protocolos', false, 0.55),
(206, 2, 'Segurança da Informação', 21, 'Criptografia', true, 0.84),
(207, 4, 'Governança e Legislação', 41, 'LGPD', true, 0.97),
(415, 1, 'Banco de Dados', 13, 'SGBD', true, NULL),
(520, 5, 'Engenharia de Software', 51, 'Princípios de Projeto', true, 0.9);

INSERT INTO fx_questao_tecnologia (questao_id, tecnologia_id, tecnologia, categoria, confianca) VALUES
(415, 1, 'PostgreSQL', 'tecnologia', 0.99),
(205, 2, 'TLS', 'tecnologia', 0.9);

-- O recorte 900 é do texto de apoio: aparece repetido em 205 e 206 (origem = 'apoio').
INSERT INTO fx_questao_recorte (questao_id, recorte_id, origem, letra_alternativa, tipo, pagina,
  caminho_relativo, ordem) VALUES
(102, 801, 'questao', NULL, 'figura', 7, 'cesgranrio/2023/p10/q32_fig1.png', 1),
(205, 900, 'apoio', NULL, 'figura', 12, 'cebraspe/2022/p20/apoio_cb1a1.png', 1),
(206, 900, 'apoio', NULL, 'figura', 12, 'cebraspe/2022/p20/apoio_cb1a1.png', 1),
(310, 802, 'questao', NULL, 'codigo', 3, 'fgv/p31/q12_codigo.png', 1),
(311, 803, 'questao', 'A', 'figura', 4, 'fgv/p31/q13_a.png', 1),
(311, 804, 'questao', 'B', 'figura', 4, 'fgv/p31/q13_b.png', 2),
(311, 805, 'questao', 'C', 'figura', 4, 'fgv/p31/q13_c_inexistente.png', 3);
